Helm restrict resources
rathberm/superset pull request #1
Opened 2022-05-12 08:17 UTC by rathberm

### SUMMARY

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

### TESTING INSTRUCTIONS

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

2022-05-12 09:56 UTC, danielhass requested changes

2022-05-12 09:56 UTC, danielhass commented on helm/superset/values.yaml
> +  # these setting will overwrite Values.resources
I would suggest that we extend this comment and align it with the other ones, some along those lines:

`Resource settings for the supersetNode pods - these settings overwrite might existing values from the global resources object defined above.`

This should be altered for all other specific resource settings as well

2022-05-12 09:56 UTC, danielhass commented on helm/superset/values.yaml
> +  # these setting will overwrite Values.resources
Furthermore I would also alter the following comment: https://github.com/rathberm/superset/pull/1/files#diff-e5bd590aeb8a54f45bf03f06039525bcf6eb92b24020a1b8634d2fb05cc8ca75L202

It should reflect the changes introduced by you and inform the user that specific settings can be entered below an explain which values take precedence.

2022-05-12 09:57 UTC, danielhass commented on helm/superset/values.yaml
> +  # these setting will overwrite Values.resources
The above link seems to be broken, what I'm referencing is the comment of the global resources setting:
```
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
```

2022-05-13 05:17 UTC, rathberm commented on helm/superset/values.yaml
> +  # these setting will overwrite Values.resources
@danielhass please check out the changes I introduced.

2022-05-17 08:07 UTC, closed without merging